In the console, type clear and hit Enter or Return. 

This will clear the console output. 

Run the file once while the tasks are longer. 

Copy and paste the terminal results (when task_duration is 3) here.

C:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes>activate

(base) C:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes>conda activate c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda

(c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda) C:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes>c:/Users/chris/Documents/44671StreamingData/streaming-02-multiple-processes/.conda/python.exe c:/Users/chris/Documents/44671StreamingData/streaming-02-multiple-processes/multiple_processes.py


STARTING UP.............................
It's 2023-01-18 at 10:52 AM

This file is running on:    nt Windows 10
The Python version is:      3.9.15

The Python interpreter is at:
 c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda\python.exe


DELETED tabble pets.
CREATED table pets.

P1 getting ready to insert Ace the Dog.
P2 getting ready to insert Cooper the Rabbit.
P3 getting ready to insert Emma the Rabbit.
P1 ADDED Ace the Dog.
P1 getting ready to insert Buddy the Dog.
P1 ADDED Buddy the Dog.
Process Process-2:
Traceback (most recent call last):
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 315, in _bootstrap       
    self.run()
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\multiple_processes.py", line 106, in process_two
    insert_pet("P2", "Cooper", "Rabbit")
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked
Process Process-3:
Traceback (most recent call last):
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 315, in _bootstrap       
    self.run()
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\multiple_processes.py", line 110, in process_three
    insert_pet("P3","Emma", "Rabbit")
  File "c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\multiple_processes.py", line 95, in insert_pet
    cur.execute(sql)
sqlite3.OperationalError: database is locked

Increasing the time results in a locked database.  

(c:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes\.conda) C:\Users\chris\Documents\44671StreamingData\streaming-02-multiple-processes>